### ISSUE TITLE
Simplify small hub management : Order Cycle IncomingProduct vs Outgoing Poducts

### ISSUE THREAD

**Issue by seballot** [openfoodfoundation/wishlist#154]
Related to #151
Happy to implement this feature myself if it's agreed

## What is the need / problem?
When creating OC, difference between IncomingProduct and OutgoingProducts is not so easy to understand. Actually I'm still not sure what is the use case were it's needed
Would be nice if, by default, we just need to choose the producers participating in this OC, and all their active products are added to the shopfront. Of course, keeping the ability to do more customization if it's needed

## Which type of users does this problem affect (and how many, if known)?
_- Hub Managers (MCFEs)_

## Potential solutions that will solve the problem ?
In the Edit Order Cycle

- hide "outgoing product" by default, add a new conf in the advanced settings "configure outgoing products"
- in the incoming products, in the products columns we could have two options -> "All" / "Custom". "Custom" will be actual behaviour. With "All", even if the producer adds new products after your order cycle is created, they will appear in your shopfront, so that's quite different that checking them all in the "custom" case

**Comment by tschumilas** [comment]
Hi @seballot - I'm not a dev,  I do user support in the OFN-Canada instance.    FYI - we have a number of hubs that use incoming and outgoing.  The typical use case:   A hub stocks products from multiple suppliers (incoming),   and this hub has multiple 'distributors'  (outgoing).  The distributor enterprise is the shopfront the consumer visits.    So -  a hub sells to 3 different neighbourhood distribution points,   or to another store ....    Its not 'just' a pick-up location.  PIckup locations in OFN are 'dumb' -  they have no functionality.  But a distributor has all the functionality of the app.  So - each 'distributor' can have their own payment methods,  and shipping methods for example.   So -  we definately need the 'outgoing' configuration in some of our more complex 'food systems'  (versus simple stores.)    But for sure -  in the most simple use case -  where a producer is selling their own stuff -   they take all 3 roles of the Order Cycle:   supplier,  coordinator,  distributor.   And this is why we have the option to configure as a 'sells own' shop (simplified order cycle layout)   versus a 'hub' shop (complex order cycle setup with incoming and outgoing.)

Love the idea of simplifications for 'sells own'  -  but I'm not sure of the implications of not requiring a payment method/shipping method setup ---  others with more tech knowledge will wade in.     Thanks for your willingness to contribute!!!   


I also want to caution about -  when the producer adds new products they will automatically appear in the hub's shop.   Often producers are 'staging' products a week ahead.   So,  as a producer,   I have products selling in a hub today.   Shop is open.  But I have new products I want to stage for selling in the NEXT order cycle of that hub.   I can add them,  and stock them,  and I know they won't show up until the hub pulls them into their shop.  Its useful for the supplier who sells to multiple hubs....  For sure if we want to go this route,  as a producer,  I could work with it.  I'm just pointing out that its not necessarily a good direction to head universally.  It might be good that a seller needs to authorize what is in their shop in some way,  rather than automate?

**Comment by seballot** [comment]
Hi @tschumilas thanks for feedback !

regarding outgoing tab, maybe instead of having a configuration to activate it in the advance settings, we could activate it as soon as multiple distributor are available? 
If only one is available, then auto select it with all products checked ? cause we will actually still need to configure following inputs : 
![image](https://user-images.githubusercontent.com/17404254/143489189-8176d0ba-9300-446d-b728-c3e604975d33.png)

re staging products, yes fair point ! it makes me think that I actually don't really know how a producer say if a product is available to be sell or not? is it just using the "on hand = 0" ? when a hub coordinator choose which variant to add from a specific producer, how do they know which one are actually available?

**Comment by tschumilas** [comment]
Right now -  if a producer is registered on the app to sell only their own products,  there is no incoming and outging tab at all.  The order cycle setup is simplified for this use case.  The farm is the supplier (incoming),  the coordinator (controlling the shop open/close dates...) and the distributor or shopfront (outgoing).  I think this works very well for simple 'sells own' farms.  For hubs ('sells any')  we need the complexity I think.


There are 2 ways that the hub - who is coordinating the order cycle -  knows what is available for sale form their suppliers:   
1. The supplier can  'select all' in the incoming section,  and then 'controls' what is available by setting the on-hand amount.  Then the hub,  only needs to select all the variants in the outgoing exchange --  and they can do this easily for EACH distributor if there is more than one.  
2. If the supplier sells to multiple hubs and wants to sell some things to hub A and other things to hub b....   then they select one by one the products they want to sell -  in each of the hubs order cycles (incoming section)  and the hubs just select everything in the outgoing exchange.
Both make it easy for the supplier to decide what is for sale,  and for the seller (hub) to add these to the shop.    If a hub does not want to sell a product that the supplier has offerred for sale -  then the hub goes to the incoming section of the order cycle and de-selects those items from the offering.

Honestly,  I think it works quite well as it is. 

Do you know about the user guide?  Just checking -  its quite detailed and covers these kind of things quite well...   It could be helpful to you :  https://guide.openfoodnetwork.org/

**Comment by seballot** [comment]
Yes I read the guide thanks :) but I missed the fact that a supplier can edit the incoming product of a OC where he's participating in, that's nice, thanks !

I understand that this complexity is needed for some case, I was just trying to find a way to make it easier to follow for small hub which have only one ditributor. It's just that we are multiple organisation in my region and we migrated together on OFN, and we all faced that same problem of not understanding this logic of incoming/outgoing
It's not a big deal, at the end we just clicked check all everywhere, but was a bit confusing. So I was just thinking we might be able to improve it. Maybe it's just not possible :) 

I still think that at least, when only one distributor candidate, selecting it by default with all variants checked will be nice, don't you think? If not, please close the issue I'm fine to let it go :)

**Comment by tschumilas** [comment]
I'm sorry -  I hope I didn't offend you @seballot  -  I just wanted to make sure that you had the guide  --  I should have assumed you did.   
I agree that the language 'incoming'  and 'outgoing' is strange to new users.  We often experience this here too.  I think your suggestion is a good one -  so don't close the issue yet --  lets see if others have opinions.   I agree with simplifying things for users wherever we can.    Again,  I"m not a dev -  so I don't know if there are other impacts of this that I am not seeing.  I am only commenting from a user support and a user myself  point of view.

**Comment by seballot** [comment]
oh no you didn't offend me at all don't worry ! :)

**Comment by RachL** [comment]
> I still think that at least, when only one distributor candidate, selecting it by default with all variants checked will be nice

Agreed! Here is a new issue to work on in the main repo : 

https://github.com/openfoodfoundation/openfoodnetwork/issues/8887

Closing here (please reopen if there are other small ideas I have missed in the discussion!)
