### ISSUE TITLE
[Products] New category "beehive products"

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/wishlist#274]
## What is the need / problem?
Beekeepers don't find a suiting category for their products (honey, pollen..). They choose "sweet products" as a default option, but one user expressed that it's not very gratifying.

## Which type of users does this problem affect (and how many, if known)?
_- Shoppers_
_- Producers_

## Potential solutions that will solve the problem  ?
Adding a new product category: for exemple  "beehive products", "honey & co" ..

**Comment by lin-d-hop** [comment]
This is handled on the instance level so no need for an issue on the global wishlist :)

**Comment by RachL** [comment]
@audez https://ofn-user-guide.gitbook.io/ofn-super-admin-guide/ofn-platform-configuration/taxonomies

However we need to proceed with caution when adding new categories. If we would have said yes to all new categories, we would have 100+ categories. Everyone things shoppers use categories when they actually use more the search bar :)

DFC has worked on a standard for the category list. In the long term I think we will want to use that standard instead of have our own list of categories. In the short term, perhaps wait until you have 5+ users asking for the same categories before making changes?
