### ISSUE TITLE
[Shopfront] Display producers by alphabetical order

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/wishlist#389]
## What is the need / problem?
By default the producers are displayed randomly in the shopfront. A user asked if it was possible to display them by alphabetical order.

## Which type of users does this problem affect (and how many, if known)?
_- Shoppers_
_- Hub Managers (MCFEs)_
_- Producers_

## Additional context
Producers are not sorted by alphabetical order.
![Screen Shot 2022-12-11 at 19 46 13](https://user-images.githubusercontent.com/28386648/206922935-951f69b1-0e0c-421c-ad8c-b7a37eda5a4a.png)

**Comment by RachL** [comment]
@audez by default _products_ are ordered by alphabetical order. That's why Boulangerie is before Soupes. If product need to be ordered by producers a workaround is to go to the shop settings and select all producers: by default the list is in alphabetical order.

![image](https://user-images.githubusercontent.com/6525576/207029307-35150c74-809a-46a3-99b0-0fcc8a666e75.png)

**Comment by audez** [comment]
Aah alphabetical order of products ! OK thanks :) 
You mean that's why Epicerie is before Boulangerie (because "Boulangerie" before "Soupes" is logical, it's alphabetical order).
Yep i already told them the option to sort by producer.

**Comment by RachL** [comment]
> You mean that's why Epicerie is before Boulangerie 

Yes the number are ordered before the letter A. Sorry I took a bad example, but the position of the two producers is not linked to their names, only the product name. So it's not random, but it's not alphabetical either for now.
