### ISSUE TITLE
Add columns to customer reports

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/wishlist#396]
## What is the need / problem?

Instead of having just the email, hubs would like to have some additional data like : 
- number of orders per customers per period
- total amount spent at the shop
- last order date

This is currently only possible if you know how to handle pivot table on spreadsheet.

## Which type of users does this problem affect (and how many, if known)?

_- Hub Managers (MCFEs)_
_- Producers_

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]

- Adding columns to current "mailing list" or "adresses" report : these info can be nice to import in newsletter tool

**Comment by RachL** [comment]
dividing in 3 issues:

1. remove the mailing list report (useless as now we can choose columns so1 customer report is enough)

2. Fix a bug displaying one customer per times they have ordered

3. Add columns

**Comment by drummer83** [comment]
>     1. remove the mailing list report (useless as now we can choose columns so1 customer report is enough)
> 
>     2. Fix a bug displaying one customer per times they have ordered
> 
>     3. Add columns

Number 2 has been fixed in [#10664](https://github.com/openfoodfoundation/openfoodnetwork/pull/10664) and [#10665](https://github.com/openfoodfoundation/openfoodnetwork/pull/10665). 

We should keep [#10706](https://github.com/openfoodfoundation/openfoodnetwork/issues/10706) in mind though and add a fix to the list probably.

**Comment by lin-d-hop** [comment]
In delivery
