### ISSUE TITLE
Producer can preview how products will appear in the store

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/wishlist#64]
## What is the need / problem?

As a producer, as I am creating or updating my products, I have no way to visualize how they will appear to my customers until I open my shop. As a profile-only producer, I have no way to visualize how they will appear until the hub(s) I sell to open shops.

Our recent mobile work has resulted in a great shop that is conveying loads of useful information to the customer. It would be nice if the producer could anticipate what the customer will see, so they can make the most use of current OFN product and shop features.

## Which type of users does this problem affect (and how many, if known)?

_- Hub Managers (MCFEs)_
_- Producers_
_- Instance Managers_

Producers with their own shops must set their enterprise to ‘invisible’ and create a test order cycle to see how products look.
Profile only producers have no way create a shop to see how their products appear to customers. They have to wait until the re-seller (hub) opens a store.

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]

From the product entry page - maybe there is a way to link to a ‘shop preview’ screen that shows that shows how that product will look when their shop is created. Even if this shopfront doesn’t take enterprise fees into account - it would still be helpful.

## Connected wishlist and discovery discussions* [list precedent discussions]

https://community.openfoodnetwork.org/t/producer-can-preview-how-products-will-appear-in-the-store/2119

## Is Papercut or feature candidate?

Feature candidate

**Comment by tschumilas** [comment]
So very excited if this moves forward.....   It will save users a lot of time.  Right now we have profile only users -  asking us if its ok if they move to 'sells own' status -  just so they can see what their products would look like.  It messes up our billing because we have to keep a manual list of these people so we don't bill them.   And we have lots of 'sells own' producers  and several of our hubs -  who set up invisible OCs just for staging their 'real' shops.      So hurray!!!!!

**Comment by aaronhirtenstein** [comment]
Is it possible to get this feature costed? The Scottish Flower Grower Collective might be able to get funding for this as it's come up as a big usability issue for their growers during user research.

**Comment by RachL** [comment]
@mariocarabotta what would be a rough estimate for the design side of things here?

**Comment by mariocarabotta** [comment]
a few questions that can help with estimate:

1. is this for an individual product preview only, or the whole shop preview?
2. is this preview only available for the individual user wanting to preview or does it need to be shared with others?
3. @aaronhirtenstein is there any detail that the Scottish Flower Grower Collective might be able to provide from their user research that might give more info regarding their need and potentially inform the design?

**Comment by aaronhirtenstein** [comment]
hi @mariocarabotta sorry I was away last week. To answer your questions:

1. individual product preview only. The need is to be able to see what your product will look like in the shop and is partly because the add product form is confusing and people missing things or put the wrong info in the wrong fields.
2. It's only come up as individual user wanting to preview it, a decent first shippable feature is that and I'd say it should be developed in such a way that we could add a shareable preview in future if desired. 
3. Not that I can think of. Usually a preview function is available at the point of creating the page / product so needs to be clearly visible at that point. I see there is now the "3 dots" feature in the new product design so a link could also appear there?

Hope this helps!

**Comment by tschumilas** [comment]
Echoing these responses.  Flower farmers in Canada have asked for this too - and we have some funding to contribute.  Individual preview,  not shareable would be the basic need.   I think flower farmers ask for this because they are selling items in slightly different ways than vegetable/cheese/meat....  farmers.  So its almost always by 'item' (verus weight, volume) .  They wrestle with options like:  do I sell by the stem?  do I sell by the bunch?  do I sell by the bunch and put 5 bunches into a bucket?....   So if they could preview their products,  they could see the cost per analysis,  and decide how they want to list.

**Comment by mariocarabotta** [comment]
thanks @aaronhirtenstein and @tschumilas, all clear!

@RachL I'd say between 1 and 1.5 days. activities would be

- first rough concept prototype to gather feedback internally here
- second round of prototype / mocks for dev + writing issue
- a bit of subsequent UI testing

**Comment by BethanOFN** [comment]
Thanks @mariocarabotta for the design work estimate - what are we looking at then for a cost estimate roughly? (@RachL ?) We can take this back to the Scottish Flower Growers then and see if we can fund together with @tschumilas 🤞

**Comment by RachL** [comment]
@mkllnk do you have a rough idea what would be the estimate on the dev side?

@BethanOFN once we have the dev side, we can add 20% of that time for product and maybe 20% for admin stuff. I think we used so far a day rate of 500 euros for funded features. Perhaps @lin-d-hop or @kirstenalarsen can confirm this rate?

**Comment by tschumilas** [comment]
I was meeting with some flower farmers here about this yesterday and they raised 2 issues to clarify:

Is the 'product preview' ONLY at the point of new product creation?   or  will the user be able to click for a product preview for any product in their product list?       Users here want to be able to preview any products in their list -  not just on creation.

Will the product preview include the product description?  -  For our users this is pretty important,  because flower farmers (unlike most produce farmers for example)  change their product descriptions weekly to inform buyers (floral designers) about the stem length and bloom stage of the product.  So as they are editing products,  they want to quickly see what the last description was they entered so they know whether or not to go to the edit product page to change it.

What price will the preview display?   So -  will it show the price as it will appear in the shop (so price + fees),   or will it show the price from their producer list?     There wasn't full agreement on which would be better -  so maybe see what the UK farmers think @BethanOFN .    Some farmers really wanted to see the 'price per unit'  calculation in the preview -  and wanted to know what the buyer was seeing (so include fees).  Others said that if this was too complicated,  having a preview with their product list price was 'good enough'.

**Comment by tschumilas** [comment]
This might mean a new estimate.  But I think OFN Canada could pay for this regardless.  We currently have some funding,  and are raising additional funds with flower hubs this season for funded features.

**Comment by RachL** [comment]
As price is define at the OC level, we would need to select an OC before showing the preview. Maybe we can leave it out of v1 as the OC selector will need to display an OC list according to permissions. It's doable but I don't know

That makes me realize I've forgotten code review and testing in my calculation above. @kirstenalarsen do you remember if the rate is covering code review or if we need to add a time estimate to it? for testing, I would use a rule like 30% of dev time. To update my message above it would be!

- 1.5 days for design
- X days of dev to be confirmed by @mkllnk (+ code review to clarify)
- X x 30% for testing
- X x 20% for product

+ 20% of total for admin overhead.

**Comment by tschumilas** [comment]
This was my 'gut' feeling too about showing the shop price.   If v1 of this is just showing the product list price, thats good.  We'll just have to make sure producers remember that this is not the sale price,  or what the cost per item will be in the shop.   But it still helps the producer see how their product will look and be described.  Thats pretty good.

**Comment by kirstenalarsen** [comment]
Hi all

I think the way we were doing this was that day rate was around 400 pounds,
so yep let's go with 550 Euros

We were then taking the dev estimate and multiplying by 4-6 times,
depending on client.

More recently I have been having FF budgets that are 50% core 50% feature,
but asking everyone to track time against the feature i.e. including
product, design, testing etc. I think this is reasonable. So this means
that you would take your dev + design + product + testing + admin estimate
and multiply it by 2, It is CRITICAL that funded features actually cover
core, not just if there's a bit leftover or we're going backwards.

I then manage the projects such that only the 50% (e.g) is available for
the project, and that includes all product, testing etc. If we don't want
to track product and testing against the project specifically then we go
back to a 4-6x (rather than 2x) the dev estimate

**Comment by mkllnk** [comment]
> do you have a rough idea what would be the estimate on the dev side?

Given that we are just replicating an existing view without any interaction in there, I would say 2 days. There are a few elements relying on the order cycle or AngularJS which we may need to leave out to save time here:
- Hide the pie chart.
- Hide the price-per-unit tooltip.
- Disable the add-button.
- Don't open product or producer modal.
- Use only producer price.

**Comment by BethanOFN** [comment]
Okay so I'd like to go back to the interested funders - I'm trying to gather together the quote and so far I have:

- 1.5 days for design
- 2 days of dev
-        2 days x 30% for testing = 0.6 days +
-        2 days x 20% for product = 0.4 days
-  = 1 day in total for testing + product
= 4.5 days overall
         + 20% of total for admin overhead = 0.9 days

= 5.4 days in total for quote.

5.4 * 2 (to include core funding as laid out by @kirstenalarsen ) = **10.8 days** @ €550/day = **€5940**

Does that seem logical?

**Comment by tschumilas** [comment]
@BethanOFN -  we have some funding in Canada for feature development to shape the platform toward the needs of cut flower farmers.  We would be able to split costs of product preview 50:50  (or something) with the UK if this works for you.  We could transfer our 50% to you if the UK is going to manage this,  or other arrangement.   But for us,  the key thing is that the product description needs to show in the preview.  (I didn't get a clear sense of whether or not that was in your spec.)

**Comment by tschumilas** [comment]
(As an aside @BethanOFN - might be worthwhile to set up a chat to go over other flower farmer features we are looking at too, to see if there are other joint funded features we could advance.   If you are game,  message me on slack and we can set something up)

**Comment by kirstenalarsen** [comment]
It will need more than 1day for product and testing
. Min 2, ideal 3

**Comment by mariocarabotta** [comment]
first prototype available [here](https://www.figma.com/proto/ddL6h7H9It5ZmUuVYQxzAD/Product-List?page-id=1083%3A2&node-id=1083-2672&viewport=418%2C519%2C0.07&t=cxHmDB4r34gl7q0V-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1083%3A2672).

to interact:

- hover on first product
- click on action button
- select preview
- move between tabs (Shop and Product details)

further notes:

- the data is a bit of a copy/paste/screenshots for now. If you need more precise and realistic product information, I can amend (it just takes a while to change all the information, I kept it lean for now).
- based on [Maikel's comment](https://github.com/openfoodfoundation/wishlist/issues/64#issuecomment-1928564182), for now I have removed the tooltips for the pie chart and the price per unit tooltip
- I am not entirely sure which values we should display for prices - please advise if I should hide more content

some conversations are happening in [slack](https://openfoodnetwork.slack.com/archives/C018S101R4J/p1719283051319609), but happy to take any feedback here as well and iterate on the concept. Thank you!

**Comment by RachL** [comment]
@BethanOFN @aaronhirtenstein do you have any feedback to provide on the prototype @mariocarabotta has shared in the previous comment ☝️ ? Many thanks!

**Comment by aaronhirtenstein** [comment]
Hiya Rachel,

I showed this to the flower grower collective here and initial views are it’s positive. The key thing they want to see is the measurement (e.g. jar) as the labelling is not clear to people and check the image looks good.

For me, the flow is not the most intuitive, I would expect to be able to have a preview option when creating or editing a product i.e. I have the option to preview, save, delete on the edit screen. Am I right in thinking preview is only available from the product list?

This means the likely behaviour for a producer is to create / update all their products, then preview them all, edit any that need fixing, then make let admin know they are finished. I would expect to preview each as I add or update them.

Hope that makes sense!

**Comment by mariocarabotta** [comment]
I see! good point @aaronhirtenstein.

how about a preview button in the edit product page too? It would open up the same preview modal.

See example here > https://www.figma.com/proto/ddL6h7H9It5ZmUuVYQxzAD/Product-List?page-id=1083%3A2&node-id=1138-368&viewport=287%2C154%2C0.14&t=EUUeqCZtE37WPgTM-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1138%3A368&show-proto-sidebar=1

**Comment by mariocarabotta** [comment]
a note related to what you mentioned: one question that will come up during development is what version of the product gets previewed. 
I don't think we have a concept of a draft, so it might only be able to preview the data that's already being saved.

In other words, if a person updates a product but doesn't save it, they will see the version that was saved before.

**Comment by aaronhirtenstein** [comment]
Hi Mario

That is useful context, thanks. In that case, I would stick with what you have designed as I would expect to preview the latest version of the product. I’m mainly drawing on my experience of Drupal where you have the option to save/publish and preview from the edit screen. But that relies on a depot of draft as you say so I think what you have designed makes total sense within the overall logic of the app. If I understand right, if you added a preview button to the product edit screen the flow would be edit product -> save (takes you to products list) -> re-edit product -> preview. If so, that would not be a great UX, in fact it’d be confusing!

**Comment by mariocarabotta** [comment]
Thank you @aaronhirtenstein.

>  If I understand right, if you added a preview button to the product edit screen the flow would be edit product -> save (takes you to products list) -> re-edit product -> preview. If so, that would not be a great UX, in fact it’d be confusing!

I double checked with the the developers, and the above quote is correct.
I agree it would be confusing, so for now we have decided to just stick with previewing from the product list view.

We might be able to introduce drafts later down the track, but for now let's start simple and see what feedback we get!

Thank you

**Comment by RachL** [comment]
New issue here: 

https://github.com/openfoodfoundation/openfoodnetwork/issues/12770
